sensor:
  - platform: command_line
    name: Toon_temp
    command: "python /config/scripts/toonclient.py -t -U <USERNAME> -P <PASSWORD>"
    unit_of_measurement: '°C'
    scan_interval: 60

  - platform: command_line
    name: Toon_PowerUsage
    command: "python /config/scripts/toonclient.py -p -U <USERNAME> -P <PASSWORD>"
    unit_of_measurement: 'Watt' 
    scan_interval: 60
    
  - platform: command_line
    name: Toon_Program_State
    command: "python /config/scripts/toonclient.py -c -U <USERNAME> -P <PASSWORD>"
    scan_interval: 60


switch:    
# The following swith set Toon to "Comfort" with the oncmd and sets Toon to "Sleep" with the offcmd.
  - platform: command_line
    switches:
      toon_prog_comfort:
        oncmd: "python /config/scripts/toonclient.py -C 0 -U <USERNAME> -P <PASSWORD>"
        offcmd: "python /config/scripts/toonclient.py -C 2 -U <USERNAME> -P <PASSWORD>"

# The following swith set Toon to "Thuis" with the oncmd and sets Toon to "Weg" with the offcmd.      
  - platform: command_line
    switches:
      toon_prog_thuis:
        oncmd: "python /config/scripts/toonclient.py -C 1 -U <USERNAME> -P <PASSWORD>"
        offcmd: "python /config/scripts/toonclient.py -C 3 -U <USERNAME> -P <PASSWORD>"
       
# Special Scenes to easily activate the different Toon Programm States
scene:
  - name: Toon Comfort
    entities:
      switch.toon_prog_comfort: on

  - name: Toon Slapen
    entities:
      switch.toon_prog_comfort: off

  - name: Toon Thuis
    entities:
      switch.toon_prog_thuis: on

  - name: Toon Weg
    entities:
      switch.toon_prog_thuis: off
