# Add the following lines to your configuration.yaml
# Make sure you enter the correct username and password credentials (without <>), which are the same you are using for your Toon mobile app

Sensor:
  - platform: command_line
    name: Toon_temp
    command: "python /config/scripts/toonclient.py -t -U <USERNAME> -P <PASSWORD>"
    unit_of_measurement: '°C'

- platform: command_line
    name: Toon_PowerUsage
    command: "python /config/scripts/toonclient.py -p -U <USERNAME> -P <PASSWORD>"
    unit_of_measurement: 'Watt'

- platform: command_line
    name: Toon_Program_State
    command: "python /config/scripts/toonclient.py -c -U <USERNAME> -P <PASSWORD>"


Switch:    
# The following swith set Toon to "Comfort" with the oncmd and sets Toon to "Sleep" with the offcmd.
 - platform: command_line
   switches:
     toon_prog_comfort:
       oncmd: "python /config/scripts/toonclient.py -C 0 -U <USERNAME> -P <PASSWORD>"
       offcmd: "python /config/scripts/toonclient.py -C 2 -U <USERNAME> -P <PASSWORD>"

# The following swith set Toon to "Thuis" with the oncmd and sets Toon to "Weg" with the offcmd.      
 - platform: command_line
   switches:
     toon_prog_thuis:
       oncmd: "python /config/scripts/toonclient.py -C 1 -U <USERNAME> -P <PASSWORD>"
       offcmd: "python /config/scripts/toonclient.py -C 3 -U <USERNAME> -P <PASSWORD>"
       
# Special Scenes to easily activate the different Toon Programm States
Scene:
 - name: Toon Comfort
   entities:
     switch.toon_prog_comfort: on

 - name: Toon Slapen
   entities:
     switch.toon_prog_comfort: off

 - name: Toon Thuis
   entities:
     switch.toon_prog_thuis: on

 - name: Toon Weg
   entities:
     switch.toon_prog_thuis: off
     
     
# Group the Toons Scenes
Group:
    Toon Programmas:
       - scene.toon_comfort
       - scene.toon_slapen
       - scene.toon_thuis
       - scene.toon_weg
       