# The following swith set Toon to "Comfort" with the oncmd and sets Toon to "Sleep" with the offcmd.      
- platform: command_line
  switches:
    toon_prog_comfort:
      oncmd: "python /config/scripts/toonclient.py -C 0 -U <USERNAME> -P <PASSWORD>"
      offcmd: "python /config/scripts/toonclient.py -C 2 -U <USERNAME> -P <PASSWORD>"

# The following swith set Toon to "Thuis" with the oncmd and sets Toon to "Weg" with the offcmd.      
- platform: command_line
  switches:
    toon_prog_thuis:
      oncmd: "python /config/scripts/toonclient.py -C 1 -U <USERNAME> -P <PASSWORD>"
      offcmd: "python /config/scripts/toonclient.py -C 3 -U <USERNAME> -P <PASSWORD>"